import Navbar from "@/components/navbar/navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import { AuthProvider } from "@/contexts/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  let isAuthenticated = false;

  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <Navbar />

          {children}
        </body>
      </AuthProvider>
    </html>
  );
}
